version: '3.7'

services:
  ecommerce-db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    driver: bridge